/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: calc.proto */

#ifndef PROTOBUF_C_calc_2eproto__INCLUDED
#define PROTOBUF_C_calc_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1001001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Calc__CalcReq Calc__CalcReq;
typedef struct _Calc__CalcRsp Calc__CalcRsp;


/* --- enums --- */


/* --- messages --- */

struct  _Calc__CalcReq
{
  ProtobufCMessage base;
  int32_t op;
  int32_t a;
  int32_t b;
};
#define CALC__CALC_REQ__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&calc__calc_req__descriptor) \
    , 0, 0, 0 }


struct  _Calc__CalcRsp
{
  ProtobufCMessage base;
  int32_t ret;
};
#define CALC__CALC_RSP__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&calc__calc_rsp__descriptor) \
    , 0 }


/* Calc__CalcReq methods */
void   calc__calc_req__init
                     (Calc__CalcReq         *message);
size_t calc__calc_req__get_packed_size
                     (const Calc__CalcReq   *message);
size_t calc__calc_req__pack
                     (const Calc__CalcReq   *message,
                      uint8_t             *out);
size_t calc__calc_req__pack_to_buffer
                     (const Calc__CalcReq   *message,
                      ProtobufCBuffer     *buffer);
Calc__CalcReq *
       calc__calc_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   calc__calc_req__free_unpacked
                     (Calc__CalcReq *message,
                      ProtobufCAllocator *allocator);
/* Calc__CalcRsp methods */
void   calc__calc_rsp__init
                     (Calc__CalcRsp         *message);
size_t calc__calc_rsp__get_packed_size
                     (const Calc__CalcRsp   *message);
size_t calc__calc_rsp__pack
                     (const Calc__CalcRsp   *message,
                      uint8_t             *out);
size_t calc__calc_rsp__pack_to_buffer
                     (const Calc__CalcRsp   *message,
                      ProtobufCBuffer     *buffer);
Calc__CalcRsp *
       calc__calc_rsp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   calc__calc_rsp__free_unpacked
                     (Calc__CalcRsp *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Calc__CalcReq_Closure)
                 (const Calc__CalcReq *message,
                  void *closure_data);
typedef void (*Calc__CalcRsp_Closure)
                 (const Calc__CalcRsp *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor calc__calc_req__descriptor;
extern const ProtobufCMessageDescriptor calc__calc_rsp__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_calc_2eproto__INCLUDED */
