/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: calc.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "calc.pb-c.h"
void   calc__calc_req__init
                     (Calc__CalcReq         *message)
{
  static Calc__CalcReq init_value = CALC__CALC_REQ__INIT;
  *message = init_value;
}
size_t calc__calc_req__get_packed_size
                     (const Calc__CalcReq *message)
{
  assert(message->base.descriptor == &calc__calc_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t calc__calc_req__pack
                     (const Calc__CalcReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &calc__calc_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t calc__calc_req__pack_to_buffer
                     (const Calc__CalcReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &calc__calc_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Calc__CalcReq *
       calc__calc_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Calc__CalcReq *)
     protobuf_c_message_unpack (&calc__calc_req__descriptor,
                                allocator, len, data);
}
void   calc__calc_req__free_unpacked
                     (Calc__CalcReq *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &calc__calc_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   calc__calc_rsp__init
                     (Calc__CalcRsp         *message)
{
  static Calc__CalcRsp init_value = CALC__CALC_RSP__INIT;
  *message = init_value;
}
size_t calc__calc_rsp__get_packed_size
                     (const Calc__CalcRsp *message)
{
  assert(message->base.descriptor == &calc__calc_rsp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t calc__calc_rsp__pack
                     (const Calc__CalcRsp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &calc__calc_rsp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t calc__calc_rsp__pack_to_buffer
                     (const Calc__CalcRsp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &calc__calc_rsp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Calc__CalcRsp *
       calc__calc_rsp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Calc__CalcRsp *)
     protobuf_c_message_unpack (&calc__calc_rsp__descriptor,
                                allocator, len, data);
}
void   calc__calc_rsp__free_unpacked
                     (Calc__CalcRsp *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &calc__calc_rsp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor calc__calc_req__field_descriptors[3] =
{
  {
    "Op",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Calc__CalcReq, op),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "A",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Calc__CalcReq, a),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "B",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Calc__CalcReq, b),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned calc__calc_req__field_indices_by_name[] = {
  1,   /* field[1] = A */
  2,   /* field[2] = B */
  0,   /* field[0] = Op */
};
static const ProtobufCIntRange calc__calc_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor calc__calc_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "calc.CalcReq",
  "CalcReq",
  "Calc__CalcReq",
  "calc",
  sizeof(Calc__CalcReq),
  3,
  calc__calc_req__field_descriptors,
  calc__calc_req__field_indices_by_name,
  1,  calc__calc_req__number_ranges,
  (ProtobufCMessageInit) calc__calc_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor calc__calc_rsp__field_descriptors[1] =
{
  {
    "ret",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Calc__CalcRsp, ret),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned calc__calc_rsp__field_indices_by_name[] = {
  0,   /* field[0] = ret */
};
static const ProtobufCIntRange calc__calc_rsp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor calc__calc_rsp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "calc.CalcRsp",
  "CalcRsp",
  "Calc__CalcRsp",
  "calc",
  sizeof(Calc__CalcRsp),
  1,
  calc__calc_rsp__field_descriptors,
  calc__calc_rsp__field_indices_by_name,
  1,  calc__calc_rsp__number_ranges,
  (ProtobufCMessageInit) calc__calc_rsp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
