/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: pbrpc.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "pbrpc.pb-c.h"
void   pbcodec__pb_rpc_request__init
                     (Pbcodec__PbRpcRequest         *message)
{
  static Pbcodec__PbRpcRequest init_value = PBCODEC__PB_RPC_REQUEST__INIT;
  *message = init_value;
}
size_t pbcodec__pb_rpc_request__get_packed_size
                     (const Pbcodec__PbRpcRequest *message)
{
  assert(message->base.descriptor == &pbcodec__pb_rpc_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pbcodec__pb_rpc_request__pack
                     (const Pbcodec__PbRpcRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &pbcodec__pb_rpc_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pbcodec__pb_rpc_request__pack_to_buffer
                     (const Pbcodec__PbRpcRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &pbcodec__pb_rpc_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Pbcodec__PbRpcRequest *
       pbcodec__pb_rpc_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Pbcodec__PbRpcRequest *)
     protobuf_c_message_unpack (&pbcodec__pb_rpc_request__descriptor,
                                allocator, len, data);
}
void   pbcodec__pb_rpc_request__free_unpacked
                     (Pbcodec__PbRpcRequest *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &pbcodec__pb_rpc_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   pbcodec__pb_rpc_response__init
                     (Pbcodec__PbRpcResponse         *message)
{
  static Pbcodec__PbRpcResponse init_value = PBCODEC__PB_RPC_RESPONSE__INIT;
  *message = init_value;
}
size_t pbcodec__pb_rpc_response__get_packed_size
                     (const Pbcodec__PbRpcResponse *message)
{
  assert(message->base.descriptor == &pbcodec__pb_rpc_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pbcodec__pb_rpc_response__pack
                     (const Pbcodec__PbRpcResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &pbcodec__pb_rpc_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pbcodec__pb_rpc_response__pack_to_buffer
                     (const Pbcodec__PbRpcResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &pbcodec__pb_rpc_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Pbcodec__PbRpcResponse *
       pbcodec__pb_rpc_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Pbcodec__PbRpcResponse *)
     protobuf_c_message_unpack (&pbcodec__pb_rpc_response__descriptor,
                                allocator, len, data);
}
void   pbcodec__pb_rpc_response__free_unpacked
                     (Pbcodec__PbRpcResponse *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &pbcodec__pb_rpc_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor pbcodec__pb_rpc_request__field_descriptors[3] =
{
  {
    "Id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Pbcodec__PbRpcRequest, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Method",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Pbcodec__PbRpcRequest, method),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Params",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Pbcodec__PbRpcRequest, has_params),
    offsetof(Pbcodec__PbRpcRequest, params),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pbcodec__pb_rpc_request__field_indices_by_name[] = {
  0,   /* field[0] = Id */
  1,   /* field[1] = Method */
  2,   /* field[2] = Params */
};
static const ProtobufCIntRange pbcodec__pb_rpc_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor pbcodec__pb_rpc_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "pbcodec.PbRpcRequest",
  "PbRpcRequest",
  "Pbcodec__PbRpcRequest",
  "pbcodec",
  sizeof(Pbcodec__PbRpcRequest),
  3,
  pbcodec__pb_rpc_request__field_descriptors,
  pbcodec__pb_rpc_request__field_indices_by_name,
  1,  pbcodec__pb_rpc_request__number_ranges,
  (ProtobufCMessageInit) pbcodec__pb_rpc_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor pbcodec__pb_rpc_response__field_descriptors[3] =
{
  {
    "Id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Pbcodec__PbRpcResponse, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Result",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Pbcodec__PbRpcResponse, result),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Error",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Pbcodec__PbRpcResponse, error),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pbcodec__pb_rpc_response__field_indices_by_name[] = {
  2,   /* field[2] = Error */
  0,   /* field[0] = Id */
  1,   /* field[1] = Result */
};
static const ProtobufCIntRange pbcodec__pb_rpc_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor pbcodec__pb_rpc_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "pbcodec.PbRpcResponse",
  "PbRpcResponse",
  "Pbcodec__PbRpcResponse",
  "pbcodec",
  sizeof(Pbcodec__PbRpcResponse),
  3,
  pbcodec__pb_rpc_response__field_descriptors,
  pbcodec__pb_rpc_response__field_indices_by_name,
  1,  pbcodec__pb_rpc_response__number_ranges,
  (ProtobufCMessageInit) pbcodec__pb_rpc_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
