// Code generated by protoc-gen-go.
// source: pbrpc.proto
// DO NOT EDIT!

/*
Package pbcodec is a generated protocol buffer package.

It is generated from these files:
	pbrpc.proto

It has these top-level messages:
	PbRpcRequest
	PbRpcResponse
*/
package pbcodec

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type PbRpcRequest struct {
	Id               *uint64 `protobuf:"varint,1,req" json:"Id,omitempty"`
	Method           *string `protobuf:"bytes,2,req" json:"Method,omitempty"`
	Params           []byte  `protobuf:"bytes,3,opt" json:"Params,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PbRpcRequest) Reset()         { *m = PbRpcRequest{} }
func (m *PbRpcRequest) String() string { return proto.CompactTextString(m) }
func (*PbRpcRequest) ProtoMessage()    {}

func (m *PbRpcRequest) GetId() uint64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *PbRpcRequest) GetMethod() string {
	if m != nil && m.Method != nil {
		return *m.Method
	}
	return ""
}

func (m *PbRpcRequest) GetParams() []byte {
	if m != nil {
		return m.Params
	}
	return nil
}

type PbRpcResponse struct {
	Id               *uint64 `protobuf:"varint,1,req" json:"Id,omitempty"`
	Result           []byte  `protobuf:"bytes,2,req" json:"Result,omitempty"`
	Error            *string `protobuf:"bytes,3,opt" json:"Error,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PbRpcResponse) Reset()         { *m = PbRpcResponse{} }
func (m *PbRpcResponse) String() string { return proto.CompactTextString(m) }
func (*PbRpcResponse) ProtoMessage()    {}

func (m *PbRpcResponse) GetId() uint64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *PbRpcResponse) GetResult() []byte {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *PbRpcResponse) GetError() string {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return ""
}
