// Code generated by protoc-gen-go.
// source: calc.proto
// DO NOT EDIT!

/*
Package calc is a generated protocol buffer package.

It is generated from these files:
	calc.proto

It has these top-level messages:
	CalcReq
	CalcRsp
*/
package calc

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type CalcReq struct {
	Op               *int32 `protobuf:"varint,1,req" json:"Op,omitempty"`
	A                *int32 `protobuf:"varint,2,req" json:"A,omitempty"`
	B                *int32 `protobuf:"varint,3,req" json:"B,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CalcReq) Reset()         { *m = CalcReq{} }
func (m *CalcReq) String() string { return proto.CompactTextString(m) }
func (*CalcReq) ProtoMessage()    {}

func (m *CalcReq) GetOp() int32 {
	if m != nil && m.Op != nil {
		return *m.Op
	}
	return 0
}

func (m *CalcReq) GetA() int32 {
	if m != nil && m.A != nil {
		return *m.A
	}
	return 0
}

func (m *CalcReq) GetB() int32 {
	if m != nil && m.B != nil {
		return *m.B
	}
	return 0
}

type CalcRsp struct {
	Ret              *int32 `protobuf:"varint,1,req,name=ret" json:"ret,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CalcRsp) Reset()         { *m = CalcRsp{} }
func (m *CalcRsp) String() string { return proto.CompactTextString(m) }
func (*CalcRsp) ProtoMessage()    {}

func (m *CalcRsp) GetRet() int32 {
	if m != nil && m.Ret != nil {
		return *m.Ret
	}
	return 0
}
